import { Background } from "@/components/background";
import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import MembersImg from "public/members-img.png";

const Gallery: NextPage= () => {
  return (
    <div>
      <Head>
        <title>Bead DAO</title>
        <meta name="description" content="Generated by @rainbow-me/create-rainbowkit" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background>
        <div className="w-[100%] h-[100vh] pt-[1rem] overflow-scroll flex flex-col items-center mt-10">
          <Image
            src={MembersImg}
            alt="members gallery"
            width={650}
            height={undefined}
          />
        </div>
      </Background>
    </div>
  );
};
export default Gallery;