import type { NextPage } from "next";
import Head from "next/head";
import { useAccount } from "wagmi";
import { useEffect, useState } from "react";
import { Background } from "../components/background";
import { useRouter } from "next/router";
import { fetchEnsName } from "@wagmi/core";
import { Board } from "../components/board";
import useSWR from "swr";

const GovernanceBoard: NextPage = () => {
  const [ensName, setEnsName] = useState<string | undefined>();
  const [isLoading, setIsLoading] = useState(false);
  const { address } = useAccount();

  // const { data } = useSWR("/api/governance", async (url) =>
  //   fetch(url).then((res) => res.json())
  // );

  const { data, error } = useSWR("api/governanceBoard", async (url: string) =>
    fetch(url).then((res) => res.json())
  );

  useEffect(() => {
    async function getEnsName() {
      if (address) {
        const ensName = await fetchEnsName({
          address: address as `0x${string}`,
        });

        if (ensName) {
          setEnsName(ensName);
        }
      }
    }

    getEnsName();
  }, [address]);

  return (
    <div>
      <Head>
        <title>Bead DAO</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background display="block">
        {isLoading ? (
          <div className="flex flex-col justify-center items-center h-full">
            <div className="relative ">
              <video
                className="object-cover h-[353px] w-[367px]"
                src="/lizzlfying.webm"
                autoPlay
                loop
              />
              <div className="absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]">
                <div className="py-3 px-4 text-3xl whitespace-nowrap text-white rounded-full cursor-pointer font-bold">
                  LOADING....
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="my-o mx-auto p-2">
            <Board address={address} data={data} />
          </div>
        )}
      </Background>
    </div>
  );
};

export default GovernanceBoard;
