import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useAccount } from "wagmi";
import { Button } from "../components/button";
import { useEffect, useState } from "react";
import { Alchemy, Network, Contract } from "alchemy-sdk";
import { Background } from "../components/background";
import { NavLink } from "../components/navLink";
import Link from "next/link";

const Home: NextPage = () => {
  const links = [
    {
      link: "/scan",
      text: "contact",
    },
    {
      link: "/mint",
      text: "mint",
    },
    {
      link: "/account",
      text: "your lounge",
    },
  ];

  return (
    <div className="">
      <Head>
        <title>Bead DAO</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background height="h-[100vh]">
        <div className="h-[100%] flex flex-col justify-end items-center space-y-8">
          {links.map((item) => (
            <NavLink key={item.link} className="cursor-pointer">
              <Link href={item.link}>
                <div className="text-center text-xl font-bold first-letter:capitalize">
                  {item.text}
                </div>
              </Link>
            </NavLink>
          ))}
        </div>
      </Background>
    </div>
  );
};

export default Home;
