import type { NextPage } from "next";
import Head from "next/head";
import { Background } from "../components/background";

const Scan: NextPage = () => {
  // const { account, isConnected, isDisconnected } = useAccount();

  return (
    <div className="">
      <Head>
        <title>Bead DAO</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background height="h-[100vh]">
        <div className="flex flex-col justify-center items-center h-full">
          <a
            href="https://t.me/beaddao"
            target="_blank"
            rel="noreferrer"
            className="bg-blue-500 text-white py-4 px-6 rounded-full cursor-pointer font-bold shadow-xl"
          >
            Join Telegram
          </a>
        </div>
      </Background>
    </div>
  );
};

export default Scan;
