import type { NextPage } from "next";
import Head from "next/head";
import { Background } from "../components/background";
import Image from "next/image";
import { Button } from "../components/button";

const Scan: NextPage = () => {
  // const { account, isConnected, isDisconnected } = useAccount();

  return (
    <div className="font-[Inter]">
      <Head>
        <title>Bead DAO</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background height="h-[100vh]">
        <div className="flex flex-col justify-center items-center h-full">
          <div className="relative ">
            <video
              className="object-cover h-[353px] w-[367px]"
              src="/lizzlfying.webm"
              autoPlay
              loop
            />
            <div className="absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]">
              <a href="https://t.me/beaddao" target="_blank" rel="noreferrer">
                <Button>
                  <div className="py-3 px-4 text-[20px] whitespace-nowrap text-white rounded-full cursor-pointer font-medium">
                    Join Telegram
                  </div>
                </Button>
              </a>
            </div>
          </div>
        </div>
      </Background>
    </div>
  );
};

export default Scan;
