import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import useSWR from "swr";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import TokenGraph from "../../components/tokenGraph";

import ReactFlow, { Background, ReactFlowProvider } from "reactflow";
import { useEffect } from "react";

const Graph: NextPage = () => {
  const router = useRouter();

  const { account } = router.query;

  const { data, isLoading } = useSWR(
    account && `/api/account/${account}`,
    (url: string) => fetch(url).then((res) => res.json())
  );

  useEffect(() => {
    if (data && !data?.tokenContract) {
      toast.error("This address is not a token bound account");
    }
  }, []);

  return (
    <div className="font-[Inter]">
      <Head>
        <title>Bead DAO</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ToastContainer />
        {isLoading || !data?.tokenContract ? (
          <div className="absolute inset-0">
            <div className="z-10 absolute inset-0 flex items-center justify-center shadow">
              <div className="px-16 py-8 animate-pulse bg-white rounded-xl flex items-center justify-center">
                loading...
              </div>
            </div>
            <ReactFlow nodes={[]} edges={[]} fitView>
              <Background className="bg-gray-100" />
            </ReactFlow>
          </div>
        ) : (
          <div className="absolute inset-0">
            <ReactFlowProvider>
              <TokenGraph
                tokenContract={data?.tokenContract}
                tokenId={data?.tokenId}
              />
            </ReactFlowProvider>
          </div>
        )}
      </main>
    </div>
  );
};

export default Graph;
